[package]
name = "markflow-wasm"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
wasm-bindgen = "0.2.105"
markflow-core = { path = "../core" }
